# Generated by Django 4.2.2 on 2023-06-23 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100, null=True)),
                ('client_email', models.EmailField(max_length=254, null=True)),
                ('to_city', models.CharField(max_length=100, null=True)),
                ('to_post_code', models.CharField(max_length=100, null=True)),
                ('to_country', models.CharField(max_length=100, null=True)),
                ('invoice_date', models.DateField(null=True)),
                ('project_description', models.TextField(max_length=250, null=True)),
                ('from_street_address', models.CharField(max_length=200, null=True)),
                ('from_city', models.CharField(max_length=100)),
                ('from_post_code', models.CharField(max_length=100)),
                ('from_country', models.CharField(max_length=100)),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.invoice_status')),
            ],
        ),
    ]
