# Generated by Django 4.2.2 on 2023-06-23 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice_status',
            name='status',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
