# Generated by Django 4.2.2 on 2023-06-24 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_invoice_status_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_term',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.payment_term'),
        ),
    ]
