# Generated by Django 4.2.2 on 2023-06-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_invoice_item_invoice_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice_item',
            name='prince',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoice_item',
            name='quantaty',
            field=models.IntegerField(null=True),
        ),
    ]
