# Generated by Django 4.2.2 on 2023-06-26 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_invoice_item_prince_invoice_item_quantaty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='items',
        ),
        migrations.DeleteModel(
            name='Invoice_Item',
        ),
    ]
