# Generated by Django 4.2.2 on 2023-07-21 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_invoice_items_invoice_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='items',
        ),
        migrations.DeleteModel(
            name='Invoice_Items',
        ),
    ]
