# Generated by Django 4.2.2 on 2023-07-26 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_remove_invoice_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='items_list',
            field=models.ManyToManyField(related_name='items', to='base.invoice_items'),
        ),
    ]
