# Generated by Django 4.2.2 on 2023-07-26 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_invoice_items_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='items_list',
            field=models.ManyToManyField(blank=True, null=True, related_name='items', to='base.invoice_items'),
        ),
    ]
