# Generated by Django 4.2.2 on 2023-07-26 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_invoice_items_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='items_list',
        ),
        migrations.AddField(
            model_name='invoice',
            name='items_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.invoice_items'),
        ),
    ]
