# Generated by Django 4.2.2 on 2023-07-28 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_remove_invoice_items_list_invoice_items_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='items_list',
        ),
        migrations.AddField(
            model_name='invoice',
            name='items_list',
            field=models.ManyToManyField(related_name='items', to='base.invoice_items'),
        ),
    ]
