# Generated by Django 4.2.2 on 2023-08-02 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_invoice_items_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='items_list',
        ),
    ]
